name: Conditional check at runners

on:
  push:
    branches:
      - "production"
      - "master"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo ${{ secrets.TOKEN }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/vthacks2023:latest
          build-args: TOKEN=${{ secrets.TOKEN }}
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"
